<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sirh.Domain\Sirh.Domain.csproj" />
    <ProjectReference Include="..\Sirh.Payroll.Engine\Sirh.Payroll.Engine.csproj" />
  </ItemGroup>

</Project>
